TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 20.0
  min_vel_x: 0.03
  max_vel_y: 20.0
  min_vel_y: 0.03

  max_vel_theta:  10.0
  min_vel_theta: -10.0
  min_in_place_vel_theta: 10.0

  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_lim_theta: 5.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05

# Differential-drive robot configuration
  holonomic_robot: true

# Forward Simulation Parameters
  sim_time: 0.8
  vx_samples: 18
  vtheta_samples: 20
  sim_granularity: 0.05
